name: Fetch News

on:
  workflow_dispatch:  # This allows you to run the action on demand

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("httr", "jsonlite"))'

    - name: Fetch and Save News
      run: |
        Rscript -e '
        api_key <- Sys.getenv("NEWS_API_KEY")
        url <- paste0("https://newsapi.org/v2/top-headlines?country=us&apiKey=", api_key)
        response <- httr::GET(url)
        content <- httr::content(response, "text")
        news_data <- jsonlite::fromJSON(content)
        date <- Sys.Date()
        file_name <- paste0("data/", date, ".json")
        dir.create("data", showWarnings = FALSE)
        write(jsonlite::toJSON(news_data, pretty = TRUE), file = file_name)
        '

    - name: Commit and Push JSON Data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data/*.json
        git commit -m "Save news data for `date`"
        git push
